version: 0.2

phases:
  install:
    commands:
        - pip install --upgrade awscli
        - pip install --upgrade sphinx
        - pip install --upgrade sphinx_rtd_theme
        - pip install --upgrade sphinx_copybutton
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region ${AWS_REGION} --no-include-email)
      - echo Establishing ECR REPOSITORY_URI
      - ACCOUNT_ID=`echo ${CODEBUILD_BUILD_ARN} | cut -f5 -d':'`
      - REPO=`basename ${CODEBUILD_SOURCE_REPO_URL} .git`
      - REPOSITORY_URI=${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${REPO}
      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION:=latest}
      - PROJECT_BUCKET=${REPO//_}.app
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...  
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG        
      - echo Building python docs...  
      - cd docs/
      - make html    
      - cd ../    
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push ${REPOSITORY_URI}:latest
      - docker push ${REPOSITORY_URI}:${IMAGE_TAG}
      - echo Uploading documentation to S3...
      - aws s3 sync docs/_build/html/ s3://${PROJECT_BUCKET}/
      - aws s3 sync docs/_build/html/ s3://${PROJECT_BUCKET}/${IMAGE_TAG}/
